version: 2
executorType: machine
stages:
  build:
    workdir: /home/circleci/electronic-wechat-deb
    steps:
      - type: checkout

      - type: shell
        name: Build
        command: |
          ./build.sh