version: 2
executorType: machine
# containerInfo:
#  - image: node:7.5
stages:
  build:
    workdir: /home/circleci/electronic-wechat-deb
    environment:
      SOURCE_CODE: "https://github.com/geeeeeeeeek/electronic-wechat/archive/v2.0-rc1.tar.gz"
      UPSTREAM_VERSION: "2.0.0-rc.1"
    steps:
      - type: checkout

      - type: shell
        name: Deps
        command: |
          set -ex
          go get -u github.com/tcnksm/ghr
          sudo apt-get update
          sudo apt-get --yes install imagemagick

      - type: shell
        name: Checkout Source Code
        command: |
          set -ex
          wget $SOURCE_CODE  -O src.tar.gz
          mkdir -p src
          tar -zxvf src.tar.gz -C src --strip-components=1

      - type: shell
        name: build:linux64
        command: |
          set -ex
          cd src
          npm install
          npm run build:linux64

      - type: shell
        name: Build Deb
        command: |
          set -ex
          ./build.sh

      - type: artifacts-store
        path: dist
        destination: dist

      - type: shell
        name: ghr
        command: |
          ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME --replace $UPSTREAM_VERSION-$CIRCLE_BUILD_NUM dist/