version: 2
executorType: docker
containerInfo:
  - image: debian:8
stages:
  build:
    workdir: /home/circleci/electronic-wechat-deb
    environment:
      SOURCE_CODE: "https://github.com/geeeeeeeeek/electronic-wechat/archive/v2.0-rc1.tar.gz"
      UPSTREAM_VERSION: "2.0.0"
    steps:
      - type: checkout

      - type: shell
        name: Checkout Source Code
        command: |
          set -ex
          wget $SOURCE_CODE  -O src.tar.gz
          mkdir -p src
          tar -zxvf src.tar.gz -C src --strip-components=1
          cd src
          npm install
          npm run build:linux64

          ls dist/electronic-wechat-linux-x64
          cd ..
          ls

      - type: shell
        name: Build
        command: |
          ./build.sh

      - type: artifacts-store
        path: dist
        destination: dist